language: go
go:
  - 1.11.x
  - 1.10.x
  - tip
env:
  - GO111MODULE=off
script:
  - go get ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./ ./common ./middleware
after_success:
  - bash <(curl -s https://codecov.io/bash)
matrix:
  allow_failures:
    - go: tip